### PR TITLE
Case sensitivity fix

### PR DESCRIPTION
**Pull request by remkobrenters**

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, 

thanks for contributing. This PR should really be two seperate PR's. I'd like to accept `Fix for case sensitivity of emailaddresses`, but not the other one. That other change is not necessary imho. You can easily handle the function returning `false` in your application.

**Comment by remkobrenters** [comment]
Before I update my pull request are you sure you understand the issue I tried to solve? For example:
If you have an array with email address you want to check if they exist. After the first adress that doesn't (and mailchimp returns a 404) the "error" state persists as for each emailadress after that the 'last call' was an error (404) so the adress won't be looked up but an instant false is returned. The result is after the first non-existing adress all adresses return false.

**Comment by freekmurze** [comment]
I might be wrong but I'm thinking that if

```php
 $list = $this->lists->findByName($listName);
```
on L71 succeeds that the `!$this->lastActionSucceeded()` will return true. So there's no need to remove those lines. 

Am I missing something?

**Comment by remkobrenters** [comment]
Al right, we did some further testing. We think we found the source of the issue. In DrewM\MailChimp L316 the findHTTPStatus checks if there is a body, than searches for the 'status' value in the formatted response and returns it as an int. This value is later compared on L294. But, when a user is looked up the formattedResponse 'status' value is 'subscribed' which returns 0 if typecasted to int so the code return 'unknown error... ' on line 305 as result for a successful lookup.

Could you please test this and confirm we're right before we set out another 'false' pull request :)

ps. I think the solution is to ask Drew Mclellan to switch L316 - L318 with L320 - L322 resulting in checking the header status first before attempting to fetch a http header code from the body contents.

**Comment by remkobrenters** [comment]
I see there is a fix (10 days ago) https://github.com/drewm/mailchimp-api/commit/89b7dbc54b7ba8c2e249d6e63f66d22ecb8070f8

**Comment by freekmurze** [comment]
Does the problem persist if you update all dependencies in your project (so using the latest versions of Drew's and our package)?

**Comment by remkobrenters** [comment]
Hmm, it's fixed in the development and 2.2.2.1 tagged version but not released as separate tag (i'm not an git tag expert). As I download the latest build it's fixed, composer update on an existing vendor map won't fix it, removing the vendor map with an composer install solves the problem. Think this has to do with the 0.0.0.1 tag (as I think such a fix deserves it's own subnumber like 2.3 or something).

**Comment by freekmurze** [comment]
I've asked the author of the `mailchimp-api` package to tag a new version. So hopefully that fix will be available soon.

**Comment by freekmurze** [comment]
Thanks for the case sensitivity fix!

**Comment by remkobrenters** [comment]
Happy to help

**Pull request merged**
