### PR TITLE
Subscribe or update

### PR DESCRIPTION
**Pull request by jrean**
- [x] Subscribe or update

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thank you for this PR. I appreciate that you also updated the readme and added some tests 👍 

Right now the `subscribe` and `subscribeOrUpdate` functions are very similar. Could you try to add a new protected function to extra the sameness to? Name it `editMember` and pass it the right `http` action and the needed parameters for the call. Maybe you can come up with a better name for that function.

**Comment by jrean** [comment]
Hi @freekmurze thank you for the feedback. Can we just use the `put` method instead of the `post`. It will cover both cases and I reckon it is the best and cleanest way of handling it.
What do you think?

**Comment by freekmurze** [comment]
Ok, do it like you described. If I don't like I'll refactor it a bit myself.

Thanks!

**Comment by jrean** [comment]
@freekmurze to be sure. You mean replacing the `post` with `put` in the `subscribe()` method, right?

**Comment by jrean** [comment]
Or keeping the `subscribeOrUpdate` (following the Laravel `firstOrCreate() ...` style)?

**Comment by freekmurze** [comment]
> You mean replacing the post with put in the subscribe() method, right?

Yup

**Comment by jrean** [comment]
@freekmurze feel free to refactor (you will be for sure smarter than me). At least now we offer both options. 'Subscribe()' & 'SubscribeOrUpdate()'.

As you mentioned I would suggest adding a third method `update()' the package will be perfect :-)

**Comment by freekmurze** [comment]
Thanks!

**Comment by jrean** [comment]
🙏

**Pull request merged**
