### PR TITLE
Add support for Laravel 5.7

### PR DESCRIPTION
**Pull request by m1guelpf**
Laravel 5.7 isn't released yet, but some people are already using it. This PR allows the use of this package with Laravel 5.7

Also, please release a new version of this package (you can release a patch or a minor version) when you merge this PR, to avoid pulling `dev-master`. :wink:

:octocat:

### CODE REVIEW

**Comment by LeonAlvarez** [comment]
Duplicated #175

**Comment by m1guelpf** [comment]
ping @freekmurze

**Comment by freekmurze** [comment]
Package is now compatible with L5.7

**Comment by myurtsev** [comment]
Not working with Laravel 5.7.24 ?

I get the following error after composer require:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-newsletter ^4.3 -> satisfiable by spatie/laravel-newsletter[4.3.0].
    - Conclusion: remove laravel/framework v5.7.24
    - Conclusion: don't install laravel/framework v5.7.24

**Comment by bonucci** [comment]
Its not working also in Laravel Framework 5.7.28

**Pull request closed without merging**
