### PR TITLE
Update with new name tags

### PR DESCRIPTION
**Pull request by SimonJ**
Changed to use Mailchimps new name tags

### CODE REVIEW

**Comment by finnito** [comment]
I was just giving this package a try and was wondering why the merge tags weren't updating.
This is definitely needed - it took me a while to find it!

**Comment by SimonJ** [comment]
cc @sebastiandedeyne :)

**Comment by sebastiandedeyne** [comment]
Gonna have to ping @freekmurze for this. Aren't these tags user specified? Although if these are the defaults, I guess is makes sense.

**Comment by freekmurze** [comment]
Those tags were always named `FNAME` and `LNAME` by default on MailChimp. There's a note in the docs that points out that in all examples we've changed those to `firstName and `lastName`. Generally we don't like upper case and abbreviated indexes.

**Comment by finnito** [comment]
That's all good but if you follow the example given in the Readme:
```
Newsletter::subscribe('sam.vines@discworld.com', ['firstName'=>'Sam', 'lastName'=>'Vines']);
```
the variables are not passed to Mailchimp; however if you do it like this:
```
Newsletter::subscribe('sam.vines@discworld.com', ['FNAME'=>'Sam', 'LNAME'=>'Vines']);
```
then it works perfectly.

**Pull request closed without merging**
