### PR TITLE
Usage of SSL

### PR DESCRIPTION
**Pull request by d-jimenez**
Add the possibility to configure the SSL usage at true or false. Default is true.

### CODE REVIEW

**Comment by freekmurze** [comment]
Why wouldn't you want to use ssl?

**Comment by d-jimenez** [comment]
@freekmurze : On Windows, any method return to me with a false state because of an SSL issue with "php artisan serve". So, i would like to configure the usage of SSL in this case but not in another working environment or in production. That's why it is set at true by default.

**Comment by freekmurze** [comment]
Right now this is a breaking change. People upgrading to the latest version of the package will get an http connection, should be https. Could you fix that?

**Comment by d-jimenez** [comment]
I just added a default value at true on NewsletterServiceProvider that will enable the SSL if "laravel-newsletter.ssl" key does not exist on laravel-newsletter published configuration file. It's ok for you or i missing something else ?

**Comment by freekmurze** [comment]
That's it, thanks!

**Comment by d-jimenez** [comment]
Nice! Thanks to you :)

**Comment by freekmurze** [comment]
Slightly modified changes are available in `v3.3.0`.

**Pull request merged**
