### PR TITLE
Add interface for implementations to extend from

### LINKED ISSUE #217: This package currently forces you to use the Facade
Hi,

I've been using this package and like it, however I have noticed an issue with the implementation when injecting rather than using the facade.

Since the nulldriver and newsletter class do not implement any kind of interface it is impossible to use dependency injection since there isn't a single class or interface to inject.

If you want to be able to use both the null driver and the real class and be able to switch them out then you have to use the facade. If you use the \Spatie\Newsletter\Newsletter as a dependency then this breaks when you inject the nulldriver class instead.

Would it be possible to have them both implement an interface so people not using facades can still make use of your implementation? I would be happy to look into a PR for this if you would be willing to accept it.

Thanks

### PR DESCRIPTION
**Pull request by jamiehd**
Fixes #217 by extending from a base interface

New pull request with squashed commits from a feature branch.

### CODE REVIEW

**Comment by jamiehd** [comment]
@freekmurze how often are PRs reviewed? I would love to see this live at some point as I use this package in my own projects and it's currently more difficult to test than I would like. Thanks

**Comment by freekmurze** [comment]
I'm going to hold off on this for now. I'd like to keep this package very simple.

Feel free to create your own fork with these modifications.

**Comment by jamiehd** [comment]
@freekmurze I understand this wanting to be simple, but all this does is add an interface? At the moment it's impossible to use dependency injection if you want to test which seems restrictive to me.

**Comment by Solomon04** [comment]
@freekmurze I agree with @jamiehd here, I also can't use the package with dependency injection and using facades with phpstan just causes too many issues.

**Comment by jaketoolson** [comment]
Please reconsider, this is the only package I use where I'm forced to follow the facade pattern.

**Pull request closed without merging**
