### PR TITLE
Complete CRUD for campaigns, update subscriber details 

### PR DESCRIPTION
**Pull request by cristake**
Hi,
This is my first PR ever, so please be kind :) ... Hope it helps

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thank you very much for your contribution 👍. I'll review it in detail in the coming days.

**Comment by freekmurze** [comment]
I have some remarks on coding style and some other nitpickings.

- could you rename all usages of `$cid` to `$campaignId`. This will make the code more readable
- in `public function update($cid, $name, $value)`  could you rename `name` to `fieldName`?
- the `sendTestCampaign` accepts an array of emails (and by default an empty array). Could you change that so the its accepts but a string (a single email) or an array. If a user passes in a string just wrap it in an array. That'll make the function easier to use.
- In the example in the readme on how to update the campaign just skip using $rendered_view and directory put the `File::get` in the html key. 
- please rename `send_type` to `sendType`. I don't like underscore in parameter names, prefer camel casing.
The second example has some docblocks above them. That's not necessary, the code is clear enough.
- why add strip tags [here](https://github.com/spatie/laravel-newsletter/pull/13/files#diff-a9f5165c098beee45e6148e5731280e6R31). I believe that's a breaking change. Please remove it.

I do think the added functionality is good. That means if you fix these remarks, your changes will be pulled and tagged in a new version.

**Comment by cristake** [comment]
Hi, I've made the changes based on your remarks.

**Comment by freekmurze** [comment]
Thank you very much!

**Comment by freekmurze** [comment]
I've made some adjustments to your changes. See the current master branch. Is this ok for you or do you want to see anything changed before I tag a new version?

**Comment by cristake** [comment]
Everything's ok, thanks.
Starting from your package, I'm planning a new one to use Mailchimp API v3.0. I will let you know as soon as I will have something to show :)

**Pull request merged**
